name: utils_breeds
description: "Package of utils of Breeds APP."
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  url_launcher: ^6.2.2
  dartz: ^0.10.1
  flutter_bloc: ^8.1.3
  flutter_modular: ^5.0.3
  lottie: ^2.7.0
  oktoast: ^3.4.0
  flutter_svg: ^2.0.9
  android_id: ^0.3.3
  device_info_plus: ^9.1.1
  styled_text: ^8.1.0
  shared_preferences: ^2.2.2
  collection: ^1.18.0
  equatable: ^2.0.5

  models_breeds:
    path: ../models_breeds
  l10n_breeds:
    path: ../l10n_breeds
  network_breeds:
    path: ../network_breeds
  # models_breeds:
  #   git:
  #     url: https://github.com/wilver06w/models_breeds.git
  #     ref: main
  # l10n_breeds:
  #   git:
  #     url: https://github.com/wilver06w/l10n_breeds.git
  #     ref: main
  # network_breeds:
  #   git:
  #     url: https://github.com/wilver06w/network_breeds.git
  #     ref: main
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: